/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './resources/**/*.blade.php',
        './resources/**/*.js',
    ],
    theme: {
        extend: {
            fontFamily: {
                sans: ['"Segoe UI"', 'Roboto', '"Helvetica Neue"', 'Arial', 'sans-serif'],
            },
        },
    },
    plugins: [
        require('daisyui'),
    ],
    daisyui: {
        themes: [
            {
                wms: {
                    'primary': '#0d6efd',
                    'primary-content': '#ffffff',
                    'secondary': '#64748b',
                    'secondary-content': '#ffffff',
                    'accent': '#0891b2',
                    'accent-content': '#ffffff',
                    'neutral': '#0f172a',
                    'neutral-content': '#cbd5e1',
                    'base-100': '#ffffff',
                    'base-200': '#f4f7fc',
                    'base-300': '#dce7f5',
                    'base-content': '#1e293b',
                    'info': '#0891b2',
                    'info-content': '#ffffff',
                    'success': '#16a34a',
                    'success-content': '#ffffff',
                    'warning': '#f59e0b',
                    'warning-content': '#1e293b',
                    'error': '#dc2626',
                    'error-content': '#ffffff',
                    '--rounded-box': '0.875rem',
                    '--rounded-btn': '0.625rem',
                    '--rounded-badge': '0.625rem',
                },
                'wms-dark': {
                    'primary': '#3b82f6',
                    'primary-content': '#ffffff',
                    'secondary': '#94a3b8',
                    'secondary-content': '#0f172a',
                    'accent': '#22d3ee',
                    'accent-content': '#0f172a',
                    'neutral': '#0f172a',
                    'neutral-content': '#cbd5e1',
                    'base-100': '#17233d',
                    'base-200': '#0b1220',
                    'base-300': '#2a3a56',
                    'base-content': '#e6edf7',
                    'info': '#22d3ee',
                    'info-content': '#0f172a',
                    'success': '#22c55e',
                    'success-content': '#0f172a',
                    'warning': '#fbbf24',
                    'warning-content': '#0f172a',
                    'error': '#f87171',
                    'error-content': '#0f172a',
                    '--rounded-box': '0.875rem',
                    '--rounded-btn': '0.625rem',
                    '--rounded-badge': '0.625rem',
                },
            },
        ],
        darkTheme: 'wms-dark',
    },
};
